#!/bin/sh -l

#PBS -l nodes=1:ppn=8
#PBS -l walltime=0:30:00
#PBS -N sim
#PBS -j oe

module load cs5220
cd $PBS_O_WORKDIR
./sim -o 25 -d 5 -r 10000 -p 400 -a 0.1
./sim -o 30 -d 5 -r 10000 -p 366 -a 0.1
./sim -o 35 -d 5 -r 10000 -p 342 -a 0.1
./sim -o 50 -d 5 -r 10000 -p 300 -a 0.1
./sim -o 70 -d 5 -r 10000 -p 271 -a 0.1
./sim -o 100 -d 5 -r 10000 -p 250 -a 0.1

amplxe-cl -collect advanced-hotspots \
./sim -o 100 -d 5 -r 10000 -p 400 -a 0.1
